version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - VECTOR_DB_TYPE=chromadb
      - CHROMA_PERSIST_DIR=/app/backend/vector_db_data
      - DEFAULT_LLM_PROVIDER=openai
      - DEFAULT_MODEL=gpt-4-turbo-preview
      - EMBEDDING_MODEL=text-embedding-3-small
      - EMBEDDING_PROVIDER=openai
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=info
      - ALLOWED_ORIGINS=*
      - ENABLE_MULTI_AGENT=true
      - ENABLE_CONVERSATION_HISTORY=true
      - ENABLE_CITATIONS=true
    restart: unless-stopped
    volumes:
      - ./vector_db_data:/app/backend/vector_db_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
