[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python init_vector_db.py"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
