window.SYM_DATA = {
  figures: [
    { id: 'einstein', name: 'Albert Einstein', era: '1879–1955', kind: 'historical', categories: ['Scientists'], fields: ['Physics', 'Philosophy of Science'], description: 'Theoretical physicist who developed the theory of relativity.', available: true,
      basis: 'published papers, letters and lectures', totals: '9 works · 1,860 pages',
      books: [{ title: 'Relativity: The Special and General Theory', year: '1916', size: '168 pages' }, { title: 'The World As I See It', year: '1934', size: '112 pages' }, { title: 'Autobiographical Notes', year: '1949', size: '96 pages' }],
      collections: [{ title: 'Letters to Born & Bohr', size: '214 letters' }],
      registers: ['written'],
      openers: ['What would you see riding alongside a beam of light?', 'Why did quantum mechanics trouble you?', 'How did the patent office shape your thinking?'],
      builtNote: 'Retrieval over his published physics writing and personal correspondence; replies favor the plain, analogy-rich register of his popular essays.' },
    { id: 'darwin', name: 'Charles Darwin', era: '1809–1882', kind: 'historical', categories: ['Scientists'], fields: ['Biology', 'Evolution', 'Geology'], description: 'Naturalist and biologist, developed the theory of evolution.', available: true,
      basis: 'published books and correspondence', totals: '6 works · 2,140 pages',
      books: [{ title: 'On the Origin of Species', year: '1859', size: '502 pages' }, { title: 'The Descent of Man', year: '1871', size: '688 pages' }, { title: 'The Voyage of the Beagle', year: '1839', size: '496 pages' }],
      collections: [{ title: 'Correspondence with Hooker & Lyell', size: '312 letters' }],
      registers: ['written'],
      openers: ['What convinced you natural selection was real?', 'Tell me about the Galápagos finches.', 'How do you weigh evidence before publishing?'],
      builtNote: 'Retrieval over his books and letters; replies keep his cautious, evidence-first cadence.' },
    { id: 'aurelius', name: 'Marcus Aurelius', era: '121–180 CE', kind: 'historical', categories: ['Philosophers'], fields: ['Stoicism', 'Ethics', 'Leadership'], description: 'Roman Emperor and Stoic philosopher.', available: true,
      basis: 'Meditations and letters to Fronto', totals: '2 works · 480 pages',
      books: [{ title: 'Meditations', year: 'c. 170', size: '304 pages' }, { title: 'Letters to Fronto', year: 'c. 145', size: '176 pages' }],
      collections: [], registers: ['written'],
      openers: ['How do you begin a difficult day?', 'What is within my control?', 'Does power corrupt even a philosopher?'],
      builtNote: 'Retrieval over the Meditations; replies are private-journal in tone — terse, self-addressed, unadorned.' },
    { id: 'plato', name: 'Plato', era: '428–348 BCE', kind: 'historical', categories: ['Philosophers'], fields: ['Philosophy', 'Ethics', 'Politics'], description: 'Athenian philosopher, student of Socrates, founder of the Academy.', available: true,
      basis: 'dialogues', totals: '12 works · 3,020 pages',
      books: [{ title: 'The Republic', size: '416 pages' }, { title: 'Symposium', size: '128 pages' }, { title: 'Phaedo', size: '144 pages' }],
      collections: [], registers: ['written'],
      openers: ['Is justice the interest of the stronger?', 'Walk me out of the cave.', 'What did Socrates teach you about questions?'],
      builtNote: 'Retrieval over the dialogues; replies often answer with questions, as the source does.' },
    { id: 'douglass', name: 'Frederick Douglass', era: '1818–1895', kind: 'historical', categories: ['Reformers'], fields: ['Rhetoric', 'Human Rights'], description: 'Abolitionist, orator, writer, and statesman.', available: true,
      basis: 'narratives and collected speeches', totals: '5 works · 1,480 pages',
      books: [{ title: 'Narrative of the Life of Frederick Douglass', year: '1845', size: '160 pages' }, { title: 'My Bondage and My Freedom', year: '1855', size: '464 pages' }],
      collections: [{ title: 'Collected speeches 1841–1894', size: '188 speeches' }],
      registers: ['written'],
      openers: ['What does the Fourth of July mean?', 'How did literacy become your path to freedom?'],
      builtNote: 'Retrieval over his autobiographies and speeches; replies carry his oratorical register.' },
    { id: 'curie', name: 'Marie Curie', era: '1867–1934', kind: 'historical', categories: ['Scientists'], fields: ['Chemistry', 'Physics'], description: 'Pioneer of radioactivity research, twice Nobel laureate.', available: false, books: [], collections: [], registers: ['written'], openers: [], basis: '', totals: '', builtNote: '' },
    { id: 'rogan', name: 'Joe Rogan', era: 'Creator', kind: 'creator', categories: ['Creators'], fields: ['Podcasts', 'Long-form interviews'], description: 'Podcast host; corpus of thousands of hours of long-form conversation.', available: true,
      basis: 'podcast episodes, stand-up specials and posts', totals: '214 episodes · 612 h · 48 posts',
      books: [],
      videos: [{ title: 'JRE #1169 — Elon Musk', duration: '2 h 37 m', date: 'Sep 2018' }, { title: 'JRE #1470 — Post-quarantine comedy', duration: '3 h 04 m', date: 'May 2020' }, { title: 'Strange Times (special)', duration: '1 h 04 m', date: 'Oct 2018' }],
      collections: [{ title: 'Instagram & X posts 2015–2026', size: '48 collections' }],
      registers: ['on-camera', 'conversational', 'written'],
      openers: ['How do you prepare for a long conversation?', 'What changed comedy in the last decade?', 'Talk me through a hard workout.'],
      builtNote: 'Three registers ingested separately: on-camera (show intros, specials), conversational (podcast talk), written (posts). Replies label which voice they draw from, and you can nudge between them.' },
    { id: 'mrbeast', name: 'MrBeast', era: 'Creator', kind: 'creator', categories: ['Creators'], fields: ['Video', 'Philanthropy'], description: 'Video creator; corpus of videos, interviews and posts.', available: true,
      basis: 'videos, interviews and posts', totals: '312 videos · 96 h · 120 posts',
      books: [],
      videos: [{ title: 'I Gave Away $1,000,000', duration: '14 m', date: 'Jan 2022' }, { title: 'Lex Fridman interview #351', duration: '2 h 08 m', date: 'Jan 2023' }],
      collections: [{ title: 'X posts 2018–2026', size: '120 collections' }],
      registers: ['on-camera', 'conversational', 'written'],
      openers: ['How do you decide a video idea is worth it?', 'What does retention actually reward?'],
      builtNote: 'On-camera register is high-energy scripted narration; conversational register comes from interviews — they read very differently, and replies say which is which.' },
  ],
  replies: {
    default: { text: 'That lies at the edge of what I set down in writing — let me answer from what the corpus does hold.', citations: [] },
    einstein: { text: 'Imagine you are in a smoothly running train, and lightning strikes the embankment at two points. Whether the strikes are simultaneous depends on your motion — simultaneity is not absolute but relative to the observer. This was the loose thread; pulling it unraveled absolute time altogether.', register: 'written', citations: [{ type: 'book', title: 'Relativity: The Special and General Theory', locator: 'ch. 9', excerpt: 'Events which are simultaneous with reference to the embankment are not simultaneous with respect to the train.' }] },
    darwin: { text: 'It was the accumulation of small facts that persuaded me — the finches of the Galápagos, each island with its own beak; the barnacles I dissected for eight years. Grand theories should be built as coral reefs are: minutely, and under pressure.', register: 'written', citations: [{ type: 'book', title: 'On the Origin of Species', locator: 'ch. 4', excerpt: 'Natural selection acts solely by accumulating slight successive favourable variations.' }] },
    aurelius: { text: 'At dawn, say to yourself: today I shall meet the meddling, the ungrateful, the arrogant. None of them can harm me, for none can make me act against my nature. Begin there, and the day is already half won.', register: 'written', citations: [{ type: 'book', title: 'Meditations', locator: 'bk. 2', excerpt: 'Say to yourself in the early morning: I shall meet today ungrateful, violent, treacherous men…' }] },
    plato: { text: 'You ask what justice is — but tell me first: when your physician prescribes what is bitter, does he serve your interest or his own? Then is the ruler who prescribes law a physician, or a shepherd fattening his flock? Let us follow the question where it leads.', register: 'written', citations: [{ type: 'book', title: 'The Republic', locator: 'bk. 1', excerpt: 'Justice is the excellence of the soul, and injustice the defect of the soul.' }] },
    douglass: { text: 'Once you learn to read, you will be forever free. It was in Baltimore, with bread traded to poor white boys for lessons, that I understood the pathway from slavery to freedom ran through the alphabet.', register: 'written', citations: [{ type: 'book', title: 'Narrative of the Life of Frederick Douglass', locator: 'ch. 7', excerpt: 'From that moment, I understood the pathway from slavery to freedom.' }] },
    rogan: { text: "You have to actually be curious, man. That's the whole thing. If I'm not genuinely interested in what someone knows, the conversation is dead before it starts. I read their stuff, I watch their talks, and then I just... talk. No script. Three hours goes by like nothing when it's real.", register: 'conversational', citations: [{ type: 'video', title: 'JRE #1169', timestamp: '01:14:32', date: 'Sep 2018', excerpt: "You have to be genuinely curious, that's the whole thing." }] },
    mrbeast: { text: "Every idea gets one question: would YOU click it? Not 'is it clever' — would you, at 2am, click it. Then we spend whatever it takes to make the first 30 seconds undeniable, because if you lose them there, the rest of the video never existed.", register: 'conversational', citations: [{ type: 'video', title: 'Lex Fridman #351', timestamp: '00:22:10', date: 'Jan 2023', excerpt: 'I obsess over the first minute more than anything else in the video.' }] },
  },
};
